# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nmoek/qt_project/2020.9.1Xiangmu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nmoek/qt_project/2020.9.1Xiangmu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nmoek/qt_project/2020.9.1Xiangmu/CMakeFiles /home/nmoek/qt_project/2020.9.1Xiangmu/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nmoek/qt_project/2020.9.1Xiangmu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named BrainStorm

# Build rule for target.
BrainStorm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BrainStorm
.PHONY : BrainStorm

# fast build rule for target.
BrainStorm/fast:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/build
.PHONY : BrainStorm/fast

server/db.o: server/db.cpp.o

.PHONY : server/db.o

# target to build an object file
server/db.cpp.o:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/db.cpp.o
.PHONY : server/db.cpp.o

server/db.i: server/db.cpp.i

.PHONY : server/db.i

# target to preprocess a source file
server/db.cpp.i:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/db.cpp.i
.PHONY : server/db.cpp.i

server/db.s: server/db.cpp.s

.PHONY : server/db.s

# target to generate assembly for a file
server/db.cpp.s:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/db.cpp.s
.PHONY : server/db.cpp.s

server/main.o: server/main.cpp.o

.PHONY : server/main.o

# target to build an object file
server/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/server/main.cpp.o
.PHONY : server/main.cpp.o

server/main.i: server/main.cpp.i

.PHONY : server/main.i

# target to preprocess a source file
server/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/server/main.cpp.i
.PHONY : server/main.cpp.i

server/main.s: server/main.cpp.s

.PHONY : server/main.s

# target to generate assembly for a file
server/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/server/main.cpp.s
.PHONY : server/main.cpp.s

server/myserver.o: server/myserver.cpp.o

.PHONY : server/myserver.o

# target to build an object file
server/myserver.cpp.o:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/myserver.cpp.o
.PHONY : server/myserver.cpp.o

server/myserver.i: server/myserver.cpp.i

.PHONY : server/myserver.i

# target to preprocess a source file
server/myserver.cpp.i:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/myserver.cpp.i
.PHONY : server/myserver.cpp.i

server/myserver.s: server/myserver.cpp.s

.PHONY : server/myserver.s

# target to generate assembly for a file
server/myserver.cpp.s:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/myserver.cpp.s
.PHONY : server/myserver.cpp.s

server/tcpserver.o: server/tcpserver.cpp.o

.PHONY : server/tcpserver.o

# target to build an object file
server/tcpserver.cpp.o:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/tcpserver.cpp.o
.PHONY : server/tcpserver.cpp.o

server/tcpserver.i: server/tcpserver.cpp.i

.PHONY : server/tcpserver.i

# target to preprocess a source file
server/tcpserver.cpp.i:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/tcpserver.cpp.i
.PHONY : server/tcpserver.cpp.i

server/tcpserver.s: server/tcpserver.cpp.s

.PHONY : server/tcpserver.s

# target to generate assembly for a file
server/tcpserver.cpp.s:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/tcpserver.cpp.s
.PHONY : server/tcpserver.cpp.s

server/tcpsocket.o: server/tcpsocket.cpp.o

.PHONY : server/tcpsocket.o

# target to build an object file
server/tcpsocket.cpp.o:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/tcpsocket.cpp.o
.PHONY : server/tcpsocket.cpp.o

server/tcpsocket.i: server/tcpsocket.cpp.i

.PHONY : server/tcpsocket.i

# target to preprocess a source file
server/tcpsocket.cpp.i:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/tcpsocket.cpp.i
.PHONY : server/tcpsocket.cpp.i

server/tcpsocket.s: server/tcpsocket.cpp.s

.PHONY : server/tcpsocket.s

# target to generate assembly for a file
server/tcpsocket.cpp.s:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/tcpsocket.cpp.s
.PHONY : server/tcpsocket.cpp.s

server/thread.o: server/thread.cpp.o

.PHONY : server/thread.o

# target to build an object file
server/thread.cpp.o:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/thread.cpp.o
.PHONY : server/thread.cpp.o

server/thread.i: server/thread.cpp.i

.PHONY : server/thread.i

# target to preprocess a source file
server/thread.cpp.i:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/thread.cpp.i
.PHONY : server/thread.cpp.i

server/thread.s: server/thread.cpp.s

.PHONY : server/thread.s

# target to generate assembly for a file
server/thread.cpp.s:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/thread.cpp.s
.PHONY : server/thread.cpp.s

server/user.o: server/user.cpp.o

.PHONY : server/user.o

# target to build an object file
server/user.cpp.o:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/user.cpp.o
.PHONY : server/user.cpp.o

server/user.i: server/user.cpp.i

.PHONY : server/user.i

# target to preprocess a source file
server/user.cpp.i:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/user.cpp.i
.PHONY : server/user.cpp.i

server/user.s: server/user.cpp.s

.PHONY : server/user.s

# target to generate assembly for a file
server/user.cpp.s:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/user.cpp.s
.PHONY : server/user.cpp.s

server/util.o: server/util.cpp.o

.PHONY : server/util.o

# target to build an object file
server/util.cpp.o:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/util.cpp.o
.PHONY : server/util.cpp.o

server/util.i: server/util.cpp.i

.PHONY : server/util.i

# target to preprocess a source file
server/util.cpp.i:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/util.cpp.i
.PHONY : server/util.cpp.i

server/util.s: server/util.cpp.s

.PHONY : server/util.s

# target to generate assembly for a file
server/util.cpp.s:
	$(MAKE) -f CMakeFiles/BrainStorm.dir/build.make CMakeFiles/BrainStorm.dir/server/util.cpp.s
.PHONY : server/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... BrainStorm"
	@echo "... server/db.o"
	@echo "... server/db.i"
	@echo "... server/db.s"
	@echo "... server/main.o"
	@echo "... server/main.i"
	@echo "... server/main.s"
	@echo "... server/myserver.o"
	@echo "... server/myserver.i"
	@echo "... server/myserver.s"
	@echo "... server/tcpserver.o"
	@echo "... server/tcpserver.i"
	@echo "... server/tcpserver.s"
	@echo "... server/tcpsocket.o"
	@echo "... server/tcpsocket.i"
	@echo "... server/tcpsocket.s"
	@echo "... server/thread.o"
	@echo "... server/thread.i"
	@echo "... server/thread.s"
	@echo "... server/user.o"
	@echo "... server/user.i"
	@echo "... server/user.s"
	@echo "... server/util.o"
	@echo "... server/util.i"
	@echo "... server/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

